### ISSUE TITLE
Broken link in release comments.

### ISSUE THREAD

**Issue by danielgomezrico** [romannurik/AndroidDesignPreview#10] opened 2015-10-10 15:29 UTC
"is damaged and can't be opened" error" link broken

**Comment by romannurik** [comment] 2015-10-11 03:40
Duplicate of #1

**Closed by romannurik** 2015-10-11 03:40 UTC

**Comment by eddiecubed** [comment] 2015-10-11 15:49
He is referring to the link in the release notes for v0.3.2 is broken.
The link can be found on this page: https://github.com/romannurik/AndroidDesignPreview/releases

**Comment by romannurik** [comment] 2015-10-12 01:56
Ah, fixed.

**Comment by danielgomezrico** [comment] 2015-10-19 22:33
:+1:

**Comment by joesmarkez** [comment] 2020-04-17 08:07
Genial para poder y tener a la mano un buen trabajo
